server:
  port: 9091

spring:
  #  spring:
  #    profiles:
  #      active: dev
  application:
    name: claim-management

  datasource:
    url: jdbc:sqlserver://serverbcprogrammers.database.windows.net:1433;database=claim_management;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: adminbcp
    password: BCProgrammers1.
    initialization-mode: always